In [1]:
import numpy as np

In [2]:
twoDArray = np.array([[10,14,16,74], [45,86,72,44], [39,61,95,8], [54,33,84,3]])
print(twoDArray)

[[10 14 16 74]
 [45 86 72 44]
 [39 61 95  8]
 [54 33 84  3]]


In [3]:
print(len(twoDArray))

4


In [5]:
newTwoDArray = np.append(twoDArray, [[1,2,3,4]], axis=0)
print(newTwoDArray)
print(len(newTwoDArray))
print(len(newTwoDArray[0]))

[[10 14 16 74]
 [45 86 72 44]
 [39 61 95  8]
 [54 33 84  3]
 [ 1  2  3  4]]
5
4


In [9]:
#Accessing Element from a 2-D array

def AccessElement(array, rowIndex, colIndex):
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print("Incorrect Index")
    else:
        print(array[rowIndex][colIndex])

In [10]:
AccessElement(twoDArray,2,2)

95


In [11]:
#Traversing 2-D array

def TraverseArray(array):
    for i in range(len(array)):
        for j in range(len(array)):
            print(array[i][j])

In [12]:
TraverseArray(twoDArray)

10
14
16
74
45
86
72
44
39
61
95
8
54
33
84
3


In [13]:
def searchTDArray(array, value):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == value:
                return 'The value is located index '+str(i)+" "+str(j)
    return 'The element no found'


print(searchTDArray(twoDArray, 444))

The element no found


In [14]:
newTDArray = np.delete(twoDArray, 1, axis=1)
print(newTDArray)

[[10 16 74]
 [45 72 44]
 [39 95  8]
 [54 84  3]]
